language: rust
cache: cargo
rust:
  - nightly
matrix:
  allow-failures:
  - rust: stable
  fast_finish: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$HOME/.cargo/bin:$PATH"
- rustup component add rustfmt
- rustup component add clippy-preview

script:
  - cargo fmt --all -- --check `find src -iname "*.rs"`
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy --release -- -D clippy::all
